version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - ollama
    environment:
      - PORT=4000
      - OLLAMA_BASE_URL=http://ollama:11434
    # restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_models:/root/.ollama
    # restart: unless-stopped

  # webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: open-webui
  #   ports:
  #     - 3000:8080
  #   volumes:
  #     - webui_data:/app/backend/data
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434 # URL to Ollama API using docker
  #   depends_on:
  #     - ollama
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   # restart: unless-stopped

volumes:
  ollama_models:
  # webui_data:
