version: "3.8"

services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_models:/root/.ollama
    # restart: always

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    volumes:
      - webui_data:/app/backend/data
    environment:
      - "OLLAMA_BASE_URL=localhost:11434"
    depends_on:
      - ollama
    # restart: always

  node-api:
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - ollama
    # restart: always

volumes:
  ollama_models:
  webui_data:
